UCL-MIRSG/ansible-collection-infra

.github/workflows/molecule-provision.yml
meta/requirements.yml
roles/provision/tasks/Rocky.yml
tests/molecule/centos7/molecule.yml
tests/molecule/resources/converge.yml
tests/molecule/resources/inventory/group_vars/all.yml
tests/molecule/resources/inventory/hosts.yml

- Add a `centos7` molecule scenario (`tests/molecule/centos7/molecule.yml`) - it has two instances, one for a database and another for a web server
- Add an inventory for testing (`tests/molecule/resources/inventory/hosts.yml`)
- Add group vars for testing (`tests/molecule/resources/inventory/group_vars/all.yml`)
- Add a converge playbook for testing (`tests/molecule/resources/converge.yml`). This playbook uses tags to limit which roles are included. This means we can run molecule only on roles that have changed in a given pr.
- Add a workflow to run molecule on `mirsg.infrastructure.provision` when the provision role has changed
- Add a requirements file so we can install this collection
Edit: @drmatthews after talking offline, we'll use a single instance for running molecule tests …

Set up molecule testing

---

.github/workflows/molecule-python.yml
roles/install_python/README.md
tests/molecule/resources/inventory/group_vars/all.yml

- update README to reflect the role is now part of a collection
- add molecule inventory group vars fro `mirsg.infrastructure.install_python`
- add a workflow to run molecule on `install_python` when the role changes

Add molecule setup for `mirsg.infrastructure.install_python`

---

README.md

- update readme with installation and usage instructions
- also add code style, license, and author info

Update readme with installation and usage instructions

---

.github/workflows/molecule-provision_accounts.yml
.pre-commit-config.yaml
README.md
playbooks/setup_user_accounts.yml
roles/provision_accounts/tasks/main.yml
tests/molecule/resources/converge.yml

- add `playbooks/setup_user_accounts.yml` playbook
- uses the role `provision_accounts` to setup OS users
- update README with brief description of the playbook
- test the `provision_accounts` role via this playbook

Add playbook to setup user accounts

---

roles/postgresql/defaults/main.yml

Make `postgresql` `RPM` link OS generic

---

README.md

Without this, I cannot get it to install `main`. Moving forwards, we will probably want to specify `vx.y.z`, but for now let's fix this.

Fix collection install

---

roles/monitoring_server/defaults/main.yml
roles/monitoring_server/tasks/install_alertmanager_container.yml
roles/monitoring_server/templates/prometheus_rules.yml.j2

Changes:
- Add an `EndPointDown` alert to the `down-detector` group
- Add alerting for high inode, memory and CPU usage.
These have been tested on `ucl_test` with `mirsg_linux` as the monitoring host. Alerts can be seen at https://mirsg-linux.cs.ucl.ac.uk/prometheus/alerts

Additional alerting rules

---

.github/workflows/molecule-monitoring.yml
playbooks/install_monitoring.yml
roles/firewalld/defaults/main.yml
roles/firewalld/tasks/main.yml
roles/monitoring_client/templates/node_exporter_web.yml.j2
tests/molecule/resources/monitoring/inventory/group_vars/monitoring_client.yml
tests/molecule/resources/roles/inventory/group_vars/all.yml
tests/molecule/resources/roles/verify/firewalld.yml

Changes:
- Role name prefix for `mirsg.infrastructure.firewalld` variables
- Move firewalld role variables out of `install_monitoring.yml` playbook

firewalld vars

---

roles/monitoring_client/templates/node_exporter_web.yml.j2

Changes:
- Reinstate the `bcrypt` option for `password_hash`
This has been done since `node_exporter` expects hashed password for basic authentication to be created with `brypt`. I initially removed because the following appears when running the `monitoring_client` role:
```
AttributeError: module 'bcrypt' has no attribute '__about__'
```
The play proceeds and `node_exporter` is correctly installed. I tried pinning `bcrypt` to `4.0.1` as suggested in https://github.com/pyca/bcrypt/issues/684 but the traceback still appears. Without `bcrypt` the `node_exporter` service fails to start.

Use bcrypt with password_hash

---

roles/xnat/tasks/main.yml
tests/molecule/resources/install_xnat/inventory/group_vars/web.yml

Currently the XNAT role always attempts to copy to PG cert from the cache:
https://github.com/UCL-MIRSG/ansible-collection-infra/blob/b5385d78380444da7c10516c4e0e15bc5a7964ea/roles/xnat/tasks/main.yml#L13-L19
This should only be done if `postgresql_use_ssl` is `true`

Only copy PG cert to server when postgresql_use_ssl

---

.github/workflows/molecule-install-xnat.yml
playbooks/molecule/centos7_xnat/molecule.yml
playbooks/molecule/resources/xnat/files/resolv.conf
playbooks/molecule/rocky9_xnat/molecule.yml

- run `molecule test` on `mirsg.infrastructure.install_xnat` playbook. This is to check that the playbook can be run twice without failure, and for idempotency checks
- update the `centos7_xnat` scenario to set the `/etc/resolv.conf` for the containers. This defines nameservers for the containers, which for some reason was necessary if we also use firewalld (otherwise the containers can't reach the internet after firewalld is started)
- update the `rocky9_xnat` scenario to set the `/etc/resolv.conf` for the containers. For some reason, this is not necessary locally but is required for the tests to pass in CI

Run `molecule test` on `install_xnat` playbook

---

playbooks/molecule/resources/xnat/inventory/group_vars/all/server.yml

> The id used to refer to this site (also used to generate database ids). The Site ID must start with a letter and contain only letters, numbers and underscores. No spaces or non-alphanumeric characters.
Note, this does not address #76, but at least makes the `site_name` here valid according to XNAT.

Make `site_name` valid

---

playbooks/molecule/centos7_xnat/molecule.yml
playbooks/molecule/resources/xnat/inventory/group_vars/all/server.yml
playbooks/molecule/resources/xnat/inventory/hosts.yml
playbooks/molecule/resources/xnat/verify.yml
playbooks/molecule/rocky9_xnat/molecule.yml

Fixes https://github.com/UCL-MIRSG/ansible-collection-infra/issues/75
- fix test of `install_xnat` playbook
- rename `xnat.web.local` to `localhost` for the web container
- and use port 8080 for accessing port 80 on the web container from outside the network

Fix running `install_xnat` in molecule test environment

---

playbooks/molecule/resources/monitoring/inventory/hosts.yml
playbooks/molecule/resources/xnat/inventory/hosts.yml

Fixes #81 
- `ansible_port` is set to the default and there's no need to change it so we can safely remove it

Remove redundant `ansible_port` variable

---

.renovaterc.json

Fixes #47 
- use loose versioning for XNAT and the DXM plugin

Use loose versioning for XNAT and DXM plugin

---

roles/xnat/tasks/settings_files.yml

Fixes #76 
- check that `xnat_config.site_name` starts with a letter and contains only letters, numbers, and underscores

Add task to validate `xnat_config.site_name`

---

playbooks/upgrade_postgresql.yml
roles/postgresql/README.md
roles/postgresql/defaults/main.yml
roles/postgresql/tasks/main.yml
roles/postgresql_upgrade/README.md
roles/postgresql_upgrade/tasks/main.yml

Changes:
- Correct `hosts` for `upgrade_postgresql.yml` playbook in line with changes to playbook level group names
- Add a flag to set whether the `mirsg.infrastructure.postgresql` role should generate a new server cert
- Improve the example for how to use the `mirsg.infrastructure.postgresql_upgrade` role in a playbook

Fix upgrade postgresql playbook

---

roles/docker/tasks/main.yml
roles/provision/tasks/main.yml

Fixes #105 
- don't upgrade `docker-ce` and `docker-ce-cli` in `mirsg.infrastructure.provision`
- allow `docker-ce` and `docker-ce-cli` version to be downgraded in `mirsg.infrastructure.docker`

Install the correct versions of `docker-ce` and `docker-ce-cli`

---

playbooks/molecule/resources/xnat/inventory/group_vars/container_service.yml
playbooks/molecule/resources/xnat/inventory/group_vars/container_service_host.yml
playbooks/molecule/resources/xnat/verify.yml
roles/docker/README.md
roles/docker/defaults/main.yml
roles/docker/tasks/main.yml

Fixes #68 
Fixes #70 
- add `docker_version` variable
- verify Docker server and client versions are correct
- verify the Container Service is running
- verify an image can be added to the Container Service

Verify correct docker version is installed and the Container Service is running

---

playbooks/README.md
playbooks/restart_xnat_or_omero.yml

Add a playbook to restart database, XNAT or OMERO after an outage.
Tested on XNAT and OMERO instances deployed on `mirsg-dev.cs.ucl.ac.uk`.
Closes #118

Playbook to restart xnat and omero

---

roles/provision/README.md
roles/provision/defaults/main.yml
roles/provision/tasks/CentOS.yml

Fixes #123 
- remove previous mirrorlist from YUM repo configs
- add default baseurls that point to the CentOS 7 vault
- add variables to change the baseurl
- update README with new variables
- update README to reflect the role is now part of a collection rather than a standalone role

Use CentOS 7 vault for the YUM repos

---

playbooks/molecule/resources/monitoring/prepare.yml
playbooks/molecule/resources/shared/prepare.yml
roles/docker/molecule/resources/prepare.yml
roles/firewalld/molecule/resources/prepare.yml
roles/install_java/molecule/resources/prepare.yml
roles/install_python/molecule/resources/prepare.yml
roles/nginx/molecule/resources/prepare.yml
roles/postgresql/molecule/resources/prepare.yml
roles/postgresql_upgrade/molecule/resources/prepare.yml
roles/provision_accounts/molecule/resources/prepare.yml
roles/tomcat/molecule/resources/prepare.yml

Follow up to #124 
- molecule tests currently [fail](https://github.com/UCL-MIRSG/ansible-collection-infra/actions/runs/9939463787/job/27454089186#step:2:2460) because the default mirrorlist no longer exists since CentOS 7 is end-of-life
- set correct baseurl for YUM repos when running molecule tests on CentOS 7

Update YUM repo baseurls on CentOS 7 in prepare step for all molecule tests

---

playbooks/group_vars/xnat.yml
roles/nginx/tasks/main.yml
roles/nginx/templates/nginx_reverse_proxy.j2

Closes #119 
This is done by removing the `stream` directive from the `nginx` configuration so that the define port is only listened to by `tomcat`.

Remove stream directive, define default_dicom_listen_port directly

---

roles/firewalld/tasks/main.yml
roles/provision/README.md
roles/provision/defaults/main.yml
roles/provision/tasks/check_mounts.yml
roles/provision/tasks/main.yml
roles/xnat/tasks/plugins.yml
roles/xnat_container_service/tasks/add_container_service_hub.yml
roles/xnat_container_service/tasks/main.yml

Adds support for a container service to serve multiple XNAT clients.
The main change is modifying the provision role to allow checking of multiple mount points. Previously only a single mount point was supported, but a container server may have a separate mount for each server it supports.
Multiple mount points can be configured by defining the list `external_storage_mounts` in the host variables for the container server. If not set, the default will fall back to a list containing the single entry `external_storage_drive`, or an empty list if this is not set. This preserves existing behaviour.
The container service client role will now configure the XNAT container service "Docker image hosts" (aka hubs) from which containers can be pulled to run on XNAT. These can be defined in the …

Update container service

---

roles/docker/tasks/main.yml
roles/xnat/defaults/main.yml
roles/xnat_container_service/tasks/main.yml

- update default `xnat_version` to 1.9.1.1
- update plugins
- always restart docker after setting the daemon configuration (currently is `docker_generate_certs` is false, the daemon is not restarted and so any changes to the configuration are not applied)

Update default `xnat_version`

---

roles/xnat/defaults/main.yml

- there's an issue with 1.2.1 in which the LDAP plugin attempts to login as a different user to the one specified on the login screen (the user LDAP attempts to login with is always the same, regardless of the user logging in). Downgrading to 1.1.0 seems to resolve this issue

Downgrade LDAP plugin to 1.1.0

---

.github/workflows/molecule-docker.yaml
.github/workflows/molecule-firewalld.yaml
.github/workflows/molecule-install-omero.yaml
.github/workflows/molecule-install-xnat.yaml
.github/workflows/molecule-java.yaml
.github/workflows/molecule-monitoring.yaml
.github/workflows/molecule-nginx.yaml
.github/workflows/molecule-postgresql.yaml
.github/workflows/molecule-postgresql_upgrade.yaml
.github/workflows/molecule-provision.yaml
.github/workflows/molecule-provision_accounts.yaml
.github/workflows/molecule-python.yaml
.github/workflows/molecule-tomcat.yaml
.renovaterc.json5
molecule_configs/centos7_base_config.yml
molecule_configs/rocky9_base_config.yml
playbooks/molecule/centos7_monitoring/molecule.yml
playbooks/molecule/centos7_xnat/molecule.yml
playbooks/molecule/resources/xnat/inventory/group_vars/all/server.yml
playbooks/molecule/rocky8_omero/molecule.yml
playbooks/molecule/rocky9_monitoring/molecule.yml
playbooks/molecule/rocky9_xnat/molecule.yml
roles/xnat/defaults/main.yml

Fixes #95 
- remove DAX, Container Service, and Batch Launch plugins from list of default XNAT plugin
- add these plugins as server-specific plugins in molecule tests

Remove DAX plugin

---

playbooks/molecule/resources/xnat/inventory/group_vars/centos7.yml
playbooks/molecule/resources/xnat/inventory/group_vars/container_service.yml
playbooks/molecule/resources/xnat/inventory/group_vars/container_service_client.yml
playbooks/molecule/resources/xnat/inventory/group_vars/rocky9.yml
roles/docker/README.md
roles/docker/defaults/main.yml
roles/docker/tasks/main.yml
roles/xnat_container_service/tasks/main.yml

Fixes #148 
- add variable `docker_swarm_enabled` to the `mirsg.docker` role. If `true`, will use `community.docker.docker_swarm` to initialise a swarm on the docker host
- add variable `xnat_container_service_swarm_mode`. If `true`, the Container Service will be configured to run with Docker Swarm mode

Add support for docker swarm mode

---

galaxy.yml

Resolves #180 by specifying that the collection requires ansible.community.crypto < 3.0.0

Ensure crypto collection is v2.x.x

---

.renovaterc.json5
roles/xnat/defaults/main.yml

https://github.com/UCL-MIRSG/UCLMedicalImagingEnv/issues/461 means that any playbook that tries to access the ICR XNAT-OHIF Bitbucket repo will fail.
This is leading to:
- https://github.com/UCL-MIRSG/UCLMedicalImagingEnv/issues/462
- CI/CD failures in this repo - e.g. https://github.com/UCL-MIRSG/ansible-collection-infra/actions/runs/15974112940?pr=176
This PR updates the source URL used to https://xnat.org/files/ohif-viewer-xnat-plugin/ohif-viewer-3.7.1-fat.jar

Updated XNAT-OHIF jar source

---

playbooks/molecule/resources/xnat/inventory/group_vars/all/server.yml
roles/xnat/defaults/main.yml
roles/xnat_container_service/tasks/main.yml

- update `xnat_version` to 1.9.2.1
- update plugin versions:
- add a task to assign the `ContainerManager` role to the service admin. In the latest version of the Container Service plugin, site-admins no longer have permissions to manage the Container Service. Instead, all users that manage the plugin must be assigned the `ContainerManager` role.
- downgrade ldap plugin to 1.1.0 due to issue with plugin always attempting to log in as same user (#162)

Update default `xnat_version` to 1.9.2.1

---

.pre-commit-config.yaml
meta/omero-el8-requirements.yml

Related to #180, #181 and #183 - but also sets the restriction in the molecule requirements for OMERO on EL8 (as it may have Python 3.6 installed)
Also reverts https://github.com/UCL-MIRSG/ansible-collection-infra/commit/8113ff8ae4c57b295ca610ad910199a442151b5c so linting passes (see #188)

Ensure crypto collection is v2.x.x in molecule requirements for OMERO on EL8

---

playbooks/group_vars/xnat.yml
roles/tomcat/defaults/main.yml
roles/tomcat/molecule/resources/inventory/group_vars/tomcat10.yml

https://dlcdn.apache.org/ only has the latest versions of Tomcat, so #196 is failing CI as the older versions of the binaries are no longer accessible.

Tomcat 9.0.108 and 10.1.44

---

roles/xnat/templates/xnat-settings.json.j2

Adds [additional Settings for Restricting localdb Account Creation](https://wiki.xnat.org/documentation/configuring-authentication-providers#ConfiguringAuthenticationProviders-AdditionalSettingsforRestrictinglocaldbAccountCreation) so that we can enable built in functionality that was removed from https://github.com/UCL-MIRSG/mirsg-xnat-plugin/pull/16
The default behaviour is that:
- Hide (localdb) User Registration Options - TRUE (`securityNewUserRegistrationDisabled`)
- Disable Local DB Project Access Requests - FALSE (`securityExternalUserParDisabled`)
- Disable External Project Access Requests - FALSE (`securityLocalDbParRegistrationDisabled`)
These can be overriden in `xnat_common_config`

Additional settings for restricting local accounts
